#!/usr/bin/ruby

require 'highline/import'

class APL
  attr_accessor :difficulty, :level, :percentage

  def initialize(difficulty=:easy, level=-1, percentage=10)
    @difficulty = difficulty
    @level = level
    @percentage = percentage
  end

  def to_s
    "APL #{level} (#{difficulty.to_s.capitalize}), #{percentage}% of encounters"
  end
end

class EncounterBuilder
  attr_accessor :party_level, :max_enemies, :seed, :difficulty

  def initialize(party_level=1, max_enemies=6, difficulty=:auto)
    @party_level = party_level
    @max_enemies = max_enemies
    @seed = difficulty_seed
    @difficulty = difficulty
  end

  def difficulties
    [
      APL.new(:easy, -1, 10),
      APL.new(:average, 0, 40),
      APL.new(:challenging, 1, 25),
      APL.new(:hard, 2, 15),
      APL.new(:epic, 3, 10)
    ]
  end

  def challenge_rating
    [
      { cr: 0.125, xp: 50 },  { cr: 0.167, xp: 65 },  { cr: 0.25,	xp: 100 },
      { cr: 0.33,	xp: 135 },  { cr: 0.5, xp: 200 },   { cr: 1, xp: 400 },
      { cr: 2, xp: 600 },     { cr: 3, xp: 800 },     { cr: 4, xp: 1200 },
      { cr: 5, xp: 1600 },    { cr: 6, xp: 2400 },    { cr: 7, xp: 3200 },
      { cr: 8, xp: 4800 },    { cr: 9, xp: 6400 },    { cr: 10, xp: 9600 },
      { cr: 11, xp: 12800 },  { cr: 12, xp: 19200 },  { cr: 13, xp: 25600 },
      { cr: 14, xp: 38400 },  { cr: 15, xp: 51200 },  { cr: 16, xp: 76800 },
      { cr: 17, xp: 102400 }, { cr: 18, xp: 153600 }, { cr: 19, xp: 204800 },
      { cr: 20, xp: 307200 }, { cr: 21, xp: 409600 }, { cr: 22, xp: 614400 },
      { cr: 23, xp: 819200 }
    ]
  end

  def wealth_per_encounter
    [
      { apl: 1, slow: 170, medium: 260, fast: 400 }, { apl: 2, slow: 350, medium: 550, fast: 800 },
      { apl: 3, slow: 550, medium: 800, fast: 1200 }, { apl: 4, slow: 750, medium: 1150, fast: 1700 },
      { apl: 5, slow: 1000, medium: 1550, fast: 2300 }, { apl: 6, slow: 1350, medium: 2000, fast: 3000 },
      { apl: 7, slow: 1750, medium: 2600, fast: 3900 }, { apl: 8, slow: 2200, medium: 3350, fast: 5000 },
      { apl: 9, slow: 2850, medium: 4250, fast: 6400 }, { apl: 10, slow: 3650, medium: 5450, fast: 8200 },
      { apl: 11, slow: 4650, medium: 7000, fast: 10500 }, { apl: 12, slow: 6000, medium: 9000, fast: 13500 },
      { apl: 13, slow: 7750, medium: 11600, fast: 17500 }, { apl: 14, slow: 10000, medium: 15000, fast: 22000 },
      { apl: 15, slow: 13000, medium: 19500, fast: 29000 }, { apl: 16, slow: 16500, medium: 25000, fast: 38000 },
      { apl: 17, slow: 22000, medium: 32000, fast: 48000 }, { apl: 18, slow: 28000, medium: 41000, fast: 62000 },
      { apl: 19, slow: 35000, medium: 53000, fast: 79000 }, { apl: 20, slow: 44000, medium: 67000, fast: 100000 }
    ]
  end

  def difficulty_seed
    [].tap do |ds|
      difficulties.each do |d|
        (d.percentage / 5).times { ds << d }
      end
    end
  end

  def challenge_rating_to_cr_string(c_rating)
    case c_rating[:cr]
    when 0.125
      "CR 1/8"
    when 0.167
      "CR 1/6"
    when 0.25
      "CR 1/4"
    when 0.33
      "CR 1/3"
    when 0.5
      "CR 1/2"
    else
      "CR #{c_rating[:cr]}"
    end
  end

  def build
    encounter_apl = (@difficulty == :auto) ? @seed.sample : difficulties.select{|x| x.difficulty==@difficulty}.first
    cr = @party_level + encounter_apl.level
    xp = challenge_rating.select{|x| cr >= x[:cr]}.last[:xp]
    puts "Encounter for <#{encounter_apl.to_s}>"
    puts "Party level: #{@party_level}"
    puts "CR: #{cr}, XP: #{xp}"
    puts wealth(cr)
    puts "-"*30
    combos = [].tap do |combo|
      (1..@max_enemies).each do |i|
        combo << challenge_rating.map{|x| x[:xp]}.repeated_combination(i).select{|x| x.inject(:+) == xp}.each {|c| c.map!{|x| challenge_rating.select{|y| y[:xp] == x}.first}}
      end
    end.flatten(1)
    combos.each {|combo| puts "* #{combo.map {|x| "#{challenge_rating_to_cr_string(x)} (#{x[:xp]}XP)"}.join(", ")}"}
  end

  def wealth(cr)
    wealth_table = wealth_per_encounter.select {|x| x[:apl] == cr}.first
    "Slow: #{wealth_table[:slow]}gp, Medium: #{wealth_table[:medium]}gp, Fast: #{wealth_table[:fast]}gp"
  end
end

puts "\e[H\e[2J"
puts "Pathfinder Encounter Builder"
puts "      by Tim Gourley"
puts "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
puts ""

apl = ask("What's your average party level (APL)?", Integer) {|q| q.in = 1..20}
max_enemies = ask("What's the maximum number of enemies you want to fight?", Integer) {|q| q.in = 1..10}
difficulty = choose do |menu|
  menu.prompt = "How difficult do you want the encounter to be?"
  menu.index = :letter
  menu.index_suffix = ") "
  menu.choices(:easy, :average, :challenging, :hard, :epic, :auto)
end

eb = EncounterBuilder.new(apl, max_enemies, difficulty)
eb.build
